CREATE TABLE user_meta (
   user_name varchar,
   full_name varchar
);

insert into user_meta(user_name, full_name) values ('admin', 'דן גולן');
insert into user_meta(user_name, full_name) values ('admin_200', 'דן גולן');
insert into user_meta(user_name, full_name) values ('alon', 'אלון גולן');
insert into user_meta(user_name, full_name) values ('alon_s', 'אלון ספקטור');
insert into user_meta(user_name, full_name) values ('ameer', 'אמיר');
insert into user_meta(user_name, full_name) values ('anna', 'אנה');
insert into user_meta(user_name, full_name) values ('ariel', 'אריאל פישר');
insert into user_meta(user_name, full_name) values ('ariel_100', 'אריאל פישר');
insert into user_meta(user_name, full_name) values ('ArielG', 'אריאל גזיאל');
insert into user_meta(user_name, full_name) values ('artium', 'ארתיום');
insert into user_meta(user_name, full_name) values ('asaf', 'אסף');
insert into user_meta(user_name, full_name) values ('assif', 'אסיף גצל');
insert into user_meta(user_name, full_name) values ('avi', 'אבי קוריאט');
insert into user_meta(user_name, full_name) values ('aviad', 'אביעד כרמלי');
insert into user_meta(user_name, full_name) values ('aviram', 'אבירם');
insert into user_meta(user_name, full_name) values ('barak', 'ברק גדליה');
insert into user_meta(user_name, full_name) values ('barak_200', 'ברק גדליה');
insert into user_meta(user_name, full_name) values ('ben', 'בן צינקין');
insert into user_meta(user_name, full_name) values ('ben_b', 'בן ברק');
insert into user_meta(user_name, full_name) values ('carmit', 'כרמית ללוש');
insert into user_meta(user_name, full_name) values ('carmit_hot', 'כרמית ללוש');
insert into user_meta(user_name, full_name) values ('dalia', 'דליה בן עטר');
insert into user_meta(user_name, full_name) values ('dan_florentin', 'דן גולן');
insert into user_meta(user_name, full_name) values ('dana', 'דנה יוסקוביץ׳');
insert into user_meta(user_name, full_name) values ('dani', 'דני שטרק');
insert into user_meta(user_name, full_name) values ('daniel', 'דניאל');
insert into user_meta(user_name, full_name) values ('daniel_t', 'דניאל טיבי');
insert into user_meta(user_name, full_name) values ('David', 'דוד גלמן (מריה)');
insert into user_meta(user_name, full_name) values ('david', 'דוד גלמן (מריה)');
insert into user_meta(user_name, full_name) values ('dor', 'דור בן אלישע');
insert into user_meta(user_name, full_name) values ('dor_b', 'דור ');
insert into user_meta(user_name, full_name) values ('dor_bd', 'דור בן דויד');
insert into user_meta(user_name, full_name) values ('dor_p', 'דור פרץ');
insert into user_meta(user_name, full_name) values ('dov', 'דב רשף');
insert into user_meta(user_name, full_name) values ('dudu', 'דודו יוסף');
insert into user_meta(user_name, full_name) values ('eli_d', 'אלי דביר');
insert into user_meta(user_name, full_name) values ('elkana', 'אלקנה אפרתי');
insert into user_meta(user_name, full_name) values ('ella', 'אלה');
insert into user_meta(user_name, full_name) values ('erez', 'ארז קריאל');
insert into user_meta(user_name, full_name) values ('escape_room', 'בן צינקין');
insert into user_meta(user_name, full_name) values ('etl', 'איתאיל משרד');
insert into user_meta(user_name, full_name) values ('etl_home', 'איתאיל בית');
insert into user_meta(user_name, full_name) values ('evyatar', 'אביתר');
insert into user_meta(user_name, full_name) values ('eyal', 'אייל בן-יהודה');
insert into user_meta(user_name, full_name) values ('fadrok', 'פאדי ק׳רא');
insert into user_meta(user_name, full_name) values ('gadi', 'גדי סוקניק');
insert into user_meta(user_name, full_name) values ('gali', 'גלי חיות');
insert into user_meta(user_name, full_name) values ('getzel', 'עידן גצל');
insert into user_meta(user_name, full_name) values ('gil', 'גיל טנקוס');
insert into user_meta(user_name, full_name) values ('gilad', 'גלעד עוזיאל');
insert into user_meta(user_name, full_name) values ('gilt', 'גיל טנקוס');
insert into user_meta(user_name, full_name) values ('golan', 'שמשון גולן');
insert into user_meta(user_name, full_name) values ('hafi', 'אור לויעד');
insert into user_meta(user_name, full_name) values ('hamaoz', 'איתי חזה מנהל של המעוז');
insert into user_meta(user_name, full_name) values ('Haza', 'איתי חזה');
insert into user_meta(user_name, full_name) values ('hila', 'הילה דר');
insert into user_meta(user_name, full_name) values ('hila_s', 'הילה');
insert into user_meta(user_name, full_name) values ('hod', 'הוד');
insert into user_meta(user_name, full_name) values ('idan', 'עידן כהן');
insert into user_meta(user_name, full_name) values ('idang', 'עידן גצל');
insert into user_meta(user_name, full_name) values ('ilil', 'אילאיל ישראלי');
insert into user_meta(user_name, full_name) values ('inbaru', 'דן גולן');
insert into user_meta(user_name, full_name) values ('ishay', 'ישי אטיאס');
insert into user_meta(user_name, full_name) values ('itamar', 'איתמר');
insert into user_meta(user_name, full_name) values ('khalifa', 'חליפה חליפה');
insert into user_meta(user_name, full_name) values ('lian', 'ליאן עמדי');
insert into user_meta(user_name, full_name) values ('lior', 'ליאור');
insert into user_meta(user_name, full_name) values ('may', 'מאי');
insert into user_meta(user_name, full_name) values ('meital', 'מיטל נר');
insert into user_meta(user_name, full_name) values ('michael', 'מיכאל');
insert into user_meta(user_name, full_name) values ('miras', 'מיראס נאטור');
insert into user_meta(user_name, full_name) values ('moshe', 'משה אלעד');
insert into user_meta(user_name, full_name) values ('nimrod', 'נמרוד אלי');
insert into user_meta(user_name, full_name) values ('nimrod_h', 'נמרוד חזן');
insert into user_meta(user_name, full_name) values ('noam_b', 'נעם בריקמן');
insert into user_meta(user_name, full_name) values ('ofer', 'עופר');
insert into user_meta(user_name, full_name) values ('ofir', 'אופיר מזרחי');
insert into user_meta(user_name, full_name) values ('omer', 'עומר שייח');
insert into user_meta(user_name, full_name) values ('omry', 'עומרי תבורי');
insert into user_meta(user_name, full_name) values ('or_shaked', 'אור שאקד');
insert into user_meta(user_name, full_name) values ('oren', 'אורן ׳האפס׳ קוריאט');
insert into user_meta(user_name, full_name) values ('orit', 'אורית');
insert into user_meta(user_name, full_name) values ('paz', 'פז');
insert into user_meta(user_name, full_name) values ('rachel', 'רחל');
insert into user_meta(user_name, full_name) values ('raz', 'רז שטרק');
insert into user_meta(user_name, full_name) values ('raz_s', 'רז סגל');
insert into user_meta(user_name, full_name) values ('rina', 'רינה גולן');
insert into user_meta(user_name, full_name) values ('rom', 'רום עמית');
insert into user_meta(user_name, full_name) values ('ron', 'רון יעיש');
insert into user_meta(user_name, full_name) values ('roni', 'רוני');
insert into user_meta(user_name, full_name) values ('rotem', 'רותם');
insert into user_meta(user_name, full_name) values ('s_golan', 'שמשון גולן');
insert into user_meta(user_name, full_name) values ('segal', 'זאב סגל');
insert into user_meta(user_name, full_name) values ('sery', 'אילן סרי( חזה .)');
insert into user_meta(user_name, full_name) values ('Sery', 'אילן סרי');
insert into user_meta(user_name, full_name) values ('shaked', 'שקד רגב');
insert into user_meta(user_name, full_name) values ('sharon', 'שרון פייס');
insert into user_meta(user_name, full_name) values ('shay', 'שי קפון');
insert into user_meta(user_name, full_name) values ('shay_s', 'שי שוורץ');
insert into user_meta(user_name, full_name) values ('sheila', 'שילה');
insert into user_meta(user_name, full_name) values ('sivan', 'רועי סיון');
insert into user_meta(user_name, full_name) values ('stephan', 'סטפן שפין');
insert into user_meta(user_name, full_name) values ('tal_a', 'טל אמיר');
insert into user_meta(user_name, full_name) values ('tali', 'אופיר מזרחי');
insert into user_meta(user_name, full_name) values ('tali_l', 'טלי');
insert into user_meta(user_name, full_name) values ('tamir', 'תמיר');
insert into user_meta(user_name, full_name) values ('tankus', 'גיל טנקוס');
insert into user_meta(user_name, full_name) values ('valenci', 'יואב ולנסי');
insert into user_meta(user_name, full_name) values ('viki', 'ויקי');
insert into user_meta(user_name, full_name) values ('vitaly', 'ויטאלי');
insert into user_meta(user_name, full_name) values ('wiezel', 'אוהד ויזל');
insert into user_meta(user_name, full_name) values ('yakov', 'יעקב ירמולובסקי');
insert into user_meta(user_name, full_name) values ('yarden', 'ירדן פלג');
insert into user_meta(user_name, full_name) values ('yochi', 'יוחי');
insert into user_meta(user_name, full_name) values ('yoel', 'יואל סיגל');
insert into user_meta(user_name, full_name) values ('yosef', 'יוסף');
insert into user_meta(user_name, full_name) values ('yosi', 'אילה והבה');
insert into user_meta(user_name, full_name) values ('yuval', 'יובל זלקה');
insert into user_meta(user_name, full_name) values ('zhalaby', 'זאהי חלבי');
insert into user_meta(user_name, full_name) values ('zigi', 'יואב זינגר');
insert into user_meta(user_name, full_name) values ('zion', 'ציון');
insert into user_meta(user_name, full_name) values ('ziv', 'זיו סבן');
insert into user_meta(user_name, full_name) values ('zvi', 'צבי');

